# Generated by Django 5.2.14 on 2026-05-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_budget_id_alter_goal_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
