# Generated by Django 5.2.14 on 2026-05-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_budget_id_alter_goal_id_alter_profile_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="budget_alert_threshold",
            field=models.PositiveIntegerField(default=90),
        ),
    ]
